import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  Legend,
} from "recharts";
import {
  BookOpen,
  Building2,
  CalendarClock,
  CheckCircle2,
  Cpu,
  Download,
  FileSpreadsheet,
  FileText,
  GraduationCap,
  Sparkles,
  TriangleAlert,
  Users,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { downloadFile, gaConfig, hallStatus, seatingFor, toCsv } from "@/lib/exam-data";
import { daysOf, kpisFor, useExamData } from "@/lib/exam-store";

const chartColors = [
  "var(--color-chart-1)",
  "var(--color-chart-2)",
  "var(--color-chart-3)",
  "var(--color-chart-4)",
  "var(--color-chart-5)",
];

function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="animate-rise">
      <h2 className="text-2xl font-bold text-foreground sm:text-3xl">{title}</h2>
      <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>
    </div>
  );
}

function KpiCard({
  label,
  value,
  icon: Icon,
  hint,
  delay,
}: {
  label: string;
  value: string | number;
  icon: React.ElementType;
  hint: string;
  delay: number;
}) {
  return (
    <Card
      className="card-elevated animate-rise overflow-hidden transition-transform duration-300 hover:-translate-y-1"
      style={{ animationDelay: `${delay}ms` }}
    >
      <CardContent className="flex items-center gap-4 p-5">
        <span className="grid size-12 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary">
          <Icon className="size-6" />
        </span>
        <div className="min-w-0">
          <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
            {label}
          </p>
          <p className="font-display text-2xl font-bold text-foreground">{value}</p>
          <p className="truncate text-xs text-muted-foreground">{hint}</p>
        </div>
      </CardContent>
    </Card>
  );
}

const tooltipStyle = {
  contentStyle: {
    background: "var(--color-card)",
    border: "1px solid var(--color-border)",
    borderRadius: "0.75rem",
    color: "var(--color-foreground)",
    fontSize: "12px",
  },
};

export function DashboardSection() {
  const data = useExamData();
  const { timetable, halls, invigilators, conflicts } = data;
  const DAYS = daysOf(data);
  const kpis = kpisFor(data);
  const perSubject = timetable.map((t) => ({ name: t.code, students: t.students }));
  const utilization = halls.map((h) => ({
    hall: h.hall,
    utilization: Math.round((h.allocated / h.capacity) * 100),
  }));
  const perDay = DAYS.map((d) => ({
    day: d,
    exams: timetable.filter((t) => t.day === d).length,
  }));
  const perInvigilator = Object.entries(
    invigilators.reduce<Record<string, number>>((acc, i) => {
      const key = String(i.name ?? "Faculty");
      acc[key] = (acc[key] ?? 0) + 1;
      return acc;
    }, {}),
  ).map(([name, duties]) => ({ name, duties }));

  return (
    <div className="space-y-6">
      <SectionTitle
        title="Examination Control Dashboard"
        subtitle="Optimized schedule generated by the Genetic Algorithm engine · Odd Semester 2026"
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <KpiCard label="Total Subjects" value={kpis.subjects} icon={BookOpen} hint="Scheduled papers" delay={0} />
        <KpiCard label="Total Students" value={kpis.students} icon={GraduationCap} hint="Registered candidates" delay={60} />
        <KpiCard label="Total Invigilators" value={kpis.invigilators} icon={Users} hint="Faculty on duty" delay={120} />
        <KpiCard label="Examination Halls" value={kpis.halls} icon={Building2} hint="Active venues" delay={180} />
        <KpiCard label="Total Time Slots" value={kpis.slots} icon={CalendarClock} hint="5 days × 2 sessions" delay={240} />
        <KpiCard label="Fitness Score" value={`${kpis.fitness}%`} icon={Sparkles} hint="Best chromosome" delay={300} />
      </div>

      <div className="grid gap-5 xl:grid-cols-2">
        <Card className="card-elevated animate-rise">
          <CardHeader>
            <CardTitle className="text-base">Students per Subject</CardTitle>
          </CardHeader>
          <CardContent className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={perSubject}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
                <XAxis dataKey="name" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" interval={0} angle={-35} textAnchor="end" height={60} />
                <YAxis tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                <Tooltip {...tooltipStyle} />
                <Bar dataKey="students" fill="var(--color-chart-1)" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="card-elevated animate-rise">
          <CardHeader>
            <CardTitle className="text-base">Hall Capacity Utilization (%)</CardTitle>
          </CardHeader>
          <CardContent className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={utilization} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" horizontal={false} />
                <XAxis type="number" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                <YAxis type="category" dataKey="hall" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" width={50} />
                <Tooltip {...tooltipStyle} />
                <Bar dataKey="utilization" radius={[0, 6, 6, 0]}>
                  {utilization.map((u) => (
                    <Cell
                      key={u.hall}
                      fill={
                        u.utilization > 100
                          ? "var(--color-destructive)"
                          : u.utilization >= 85
                            ? "var(--color-warning)"
                            : "var(--color-success)"
                      }
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="card-elevated animate-rise">
          <CardHeader>
            <CardTitle className="text-base">Exam Distribution by Day</CardTitle>
          </CardHeader>
          <CardContent className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={perDay}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
                <XAxis dataKey="day" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                <YAxis allowDecimals={false} tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                <Tooltip {...tooltipStyle} />
                <Bar dataKey="exams" name="Exams" radius={[6, 6, 0, 0]} isAnimationActive={false}>
                  {perDay.map((d, i) => (
                    <Cell key={d.day} fill={chartColors[i % chartColors.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="card-elevated animate-rise">
          <CardHeader>
            <CardTitle className="text-base">Invigilator Duty Allocation</CardTitle>
          </CardHeader>
          <CardContent className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={perInvigilator}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
                <XAxis dataKey="name" tick={{ fontSize: 10 }} stroke="var(--color-muted-foreground)" interval={0} angle={-40} textAnchor="end" height={80} />
                <YAxis allowDecimals={false} tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
                <Tooltip {...tooltipStyle} />
                <Bar dataKey="duties" fill="var(--color-chart-2)" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <Card className="card-elevated animate-rise">
        <CardHeader>
          <CardTitle className="text-base">Conflict Detection Summary</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-3 sm:grid-cols-2">
          {conflicts.map((c) => (
            <div key={c.type} className="flex items-start gap-3 rounded-xl border border-border bg-muted/40 p-4">
              {c.status === "Resolved" ? (
                <CheckCircle2 className="mt-0.5 size-5 text-success" />
              ) : (
                <TriangleAlert className="mt-0.5 size-5 text-warning" />
              )}
              <div>
                <p className="text-sm font-semibold text-foreground">{c.type}</p>
                <p className="text-xs text-muted-foreground">{c.detail}</p>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}

function ExportButtons({ file, rows }: { file: string; rows: Record<string, string | number>[] }) {
  return (
    <div className="flex flex-wrap gap-2">
      <Button variant="secondary" size="sm" onClick={() => downloadFile(`${file}.csv`, toCsv(rows))}>
        <Download className="size-4" /> Download CSV
      </Button>
      <Button
        variant="secondary"
        size="sm"
        onClick={() =>
          downloadFile(`${file}.xls`, toCsv(rows), "application/vnd.ms-excel;charset=utf-8;")
        }
      >
        <FileSpreadsheet className="size-4" /> Download Excel
      </Button>
    </div>
  );
}

export function TimetableSection() {
  const { timetable } = useExamData();
  return (
    <div className="space-y-6">
      <SectionTitle
        title="Examination Timetable"
        subtitle="Conflict-free schedule produced by the best chromosome of the final generation"
      />
      <Card className="card-elevated animate-rise">
        <CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3">
          <CardTitle className="text-base">Generated Timetable · {timetable.length} papers</CardTitle>
          <ExportButtons file="vcet_timetable" rows={timetable as unknown as Record<string, string | number>[]} />
        </CardHeader>
        <CardContent className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Code</TableHead>
                <TableHead>Subject</TableHead>
                <TableHead>Teacher</TableHead>
                <TableHead>Hall</TableHead>
                <TableHead>Day</TableHead>
                <TableHead>Time</TableHead>
                <TableHead className="text-right">Students</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {timetable.map((t) => (
                <TableRow key={t.code} className="transition-colors hover:bg-accent/40">
                  <TableCell className="font-mono text-xs text-muted-foreground">{t.code}</TableCell>
                  <TableCell className="font-medium">{t.subject}</TableCell>
                  <TableCell>{t.teacher}</TableCell>
                  <TableCell>
                    <Badge variant="secondary">{t.hall}</Badge>
                  </TableCell>
                  <TableCell>{t.day}</TableCell>
                  <TableCell className="whitespace-nowrap">{t.time}</TableCell>
                  <TableCell className="text-right font-semibold">{t.students}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

export function HallSection() {
  const { halls } = useExamData();
  return (
    <div className="space-y-6">
      <SectionTitle title="Hall Allocation" subtitle="Live capacity status across all examination venues" />
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {halls.map((h, i) => {
          const status = hallStatus(h);
          const pct = Math.round((h.allocated / h.capacity) * 100);
          return (
            <Card
              key={h.hall}
              className="card-elevated animate-rise transition-transform duration-300 hover:-translate-y-1"
              style={{ animationDelay: `${i * 60}ms` }}
            >
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="font-display text-lg">Hall {h.hall}</CardTitle>
                <Badge
                  className={
                    status.tone === "success"
                      ? "bg-success text-success-foreground"
                      : status.tone === "warning"
                        ? "bg-warning text-warning-foreground"
                        : "bg-destructive text-destructive-foreground"
                  }
                >
                  {status.label}
                </Badge>
              </CardHeader>
              <CardContent className="space-y-3">
                <Progress value={Math.min(pct, 100)} />
                <div className="grid grid-cols-3 gap-2 text-center text-xs">
                  <div className="rounded-lg bg-muted p-2">
                    <p className="text-muted-foreground">Capacity</p>
                    <p className="text-base font-semibold text-foreground">{h.capacity}</p>
                  </div>
                  <div className="rounded-lg bg-muted p-2">
                    <p className="text-muted-foreground">Allocated</p>
                    <p className="text-base font-semibold text-foreground">{h.allocated}</p>
                  </div>
                  <div className="rounded-lg bg-muted p-2">
                    <p className="text-muted-foreground">Remaining</p>
                    <p className="text-base font-semibold text-foreground">{h.capacity - h.allocated}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

export function InvigilatorSection() {
  const { invigilators } = useExamData();
  return (
    <div className="space-y-6">
      <SectionTitle title="Invigilator Allocation" subtitle="Duty chart with balanced workload distribution" />
      <Card className="card-elevated animate-rise">
        <CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3">
          <CardTitle className="text-base">Duty Chart</CardTitle>
          <ExportButtons file="vcet_invigilators" rows={invigilators as unknown as Record<string, string | number>[]} />
        </CardHeader>
        <CardContent className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Invigilator</TableHead>
                <TableHead>Assigned Hall</TableHead>
                <TableHead>Assigned Subject</TableHead>
                <TableHead>Exam Day</TableHead>
                <TableHead>Exam Time</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {invigilators.map((inv, i) => (
                <TableRow key={`${inv.name}-${i}`} className="transition-colors hover:bg-accent/40">
                  <TableCell className="font-medium">{inv.name}</TableCell>
                  <TableCell>
                    <Badge variant="secondary">{inv.hall}</Badge>
                  </TableCell>
                  <TableCell>{inv.subject}</TableCell>
                  <TableCell>{inv.day}</TableCell>
                  <TableCell className="whitespace-nowrap">{inv.time}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

export function SeatingSection() {
  const { halls } = useExamData();
  return (
    <div className="space-y-6">
      <SectionTitle title="Seating Arrangement" subtitle="Hall-wise register number grid with alternate-column mixing" />
      <div className="grid gap-5 xl:grid-cols-2">
        {halls.map((h, i) => {
          const { rows } = seatingFor(h.hall, Math.min(h.allocated, 30));
          return (
            <Card key={h.hall} className="card-elevated animate-rise" style={{ animationDelay: `${i * 60}ms` }}>
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="font-display text-lg">Hall {h.hall}</CardTitle>
                <span className="text-xs text-muted-foreground">{h.allocated} candidates</span>
              </CardHeader>
              <CardContent className="space-y-2">
                {rows.map((row, r) => (
                  <div key={r} className="grid grid-cols-5 gap-2">
                    {row.map((seat) => (
                      <div
                        key={seat}
                        className="rounded-lg border border-border bg-muted/50 py-2 text-center font-mono text-xs text-foreground transition-colors hover:border-primary hover:bg-primary/10"
                      >
                        {seat}
                      </div>
                    ))}
                  </div>
                ))}
                <p className="pt-1 text-xs text-muted-foreground">Showing first {rows.length * 5} seats of {h.allocated}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

export function GaSection() {
  const data = useExamData();
  const { evolution } = data;
  const kpis = kpisFor(data);
  return (
    <div className="space-y-6">
      <SectionTitle title="Genetic Algorithm Engine" subtitle="Evolution parameters and convergence of the scheduling population" />
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        {[
          { label: "Population Size", value: gaConfig.populationSize },
          { label: "Generations", value: gaConfig.generations },
          { label: "Mutation Rate", value: gaConfig.mutationRate },
          { label: "Elite Size", value: gaConfig.eliteSize },
          { label: "Current Fitness", value: `${kpis.fitness}%` },
        ].map((p, i) => (
          <Card key={p.label} className="card-elevated animate-rise" style={{ animationDelay: `${i * 60}ms` }}>
            <CardContent className="p-5">
              <p className="text-xs uppercase tracking-wider text-muted-foreground">{p.label}</p>
              <p className="font-display text-2xl font-bold text-foreground">{p.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>
      <Card className="card-elevated animate-rise">
        <CardHeader>
          <CardTitle className="text-base">Generation vs Fitness</CardTitle>
        </CardHeader>
        <CardContent className="h-80">
          {evolution.length === 0 && (
            <p className="pb-3 text-xs text-muted-foreground">
              Upload data and generate a timetable to see live convergence.
            </p>
          )}
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={evolution}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
              <XAxis dataKey="generation" tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
              <YAxis domain={[0, 100]} tick={{ fontSize: 11 }} stroke="var(--color-muted-foreground)" />
              <Tooltip {...tooltipStyle} />
              <Legend wrapperStyle={{ fontSize: 12 }} />
              <Line type="monotone" dataKey="best" name="Best Fitness" stroke="var(--color-chart-1)" strokeWidth={3} dot={false} />
              <Line type="monotone" dataKey="average" name="Average Fitness" stroke="var(--color-chart-3)" strokeWidth={2} strokeDasharray="5 4" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>
    </div>
  );
}

export function ReportsSection() {
  const { timetable, halls, invigilators, evolution } = useExamData();
  const reports = [
    { name: "Timetable Report", rows: timetable as unknown as Record<string, string | number>[], file: "timetable_report" },
    { name: "Hall Allocation Report", rows: halls as unknown as Record<string, string | number>[], file: "hall_report" },
    { name: "Invigilator Report", rows: invigilators as unknown as Record<string, string | number>[], file: "invigilator_report" },
    {
      name: "Seating Arrangement Report",
      rows: halls.map((h) => ({ hall: h.hall, seats: h.allocated, layout: "5 per row" })),
      file: "seating_report",
    },
    { name: "Fitness Report", rows: evolution as unknown as Record<string, string | number>[], file: "fitness_report" },
  ];

  return (
    <div className="space-y-6">
      <SectionTitle title="Reports & Exports" subtitle="Download exam office documents in CSV, Excel or printable PDF" />
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {reports.map((r, i) => (
          <Card key={r.name} className="card-elevated animate-rise" style={{ animationDelay: `${i * 60}ms` }}>
            <CardHeader className="flex flex-row items-center gap-3">
              <span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary">
                <FileText className="size-5" />
              </span>
              <CardTitle className="text-base">{r.name}</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-wrap gap-2">
              <Button size="sm" variant="secondary" onClick={() => downloadFile(`${r.file}.csv`, toCsv(r.rows))}>
                CSV
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={() => downloadFile(`${r.file}.xls`, toCsv(r.rows), "application/vnd.ms-excel;charset=utf-8;")}
              >
                Excel
              </Button>
              <Button size="sm" onClick={() => window.print()}>
                PDF
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

export function AboutSection() {
  const details = [
    ["Project Name", "University Examination Timetable Scheduler Using Genetic Algorithm"],
    ["Domain", "Artificial Intelligence"],
    ["Sub Domain", "Optimization and Scheduling"],
    ["Algorithm", "Genetic Algorithm"],
    ["Developed For", "Velalar College of Engineering and Technology (Autonomous)"],
    ["Department", "Artificial Intelligence and Data Science"],
  ];
  return (
    <div className="space-y-6">
      <SectionTitle title="About the Project" subtitle="Final year project · Department of AI & Data Science" />
      <Card className="card-elevated animate-rise">
        <CardContent className="divide-y divide-border p-0">
          {details.map(([k, v]) => (
            <div key={k} className="grid gap-1 p-5 sm:grid-cols-3">
              <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{k}</p>
              <p className="text-sm font-medium text-foreground sm:col-span-2">{v}</p>
            </div>
          ))}
        </CardContent>
      </Card>
      <Card className="card-elevated animate-rise">
        <CardHeader className="flex flex-row items-center gap-3">
          <Cpu className="size-5 text-primary" />
          <CardTitle className="text-base">Methodology</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-muted-foreground">
          <p>
            Each chromosome encodes a complete examination schedule mapping subjects to halls, days
            and sessions. Fitness penalises student clashes, hall overloads and invigilator
            conflicts, while rewarding an even spread of papers across days.
          </p>
          <p>
            Tournament selection, single-point crossover and adaptive mutation evolve the population
            over {gaConfig.generations} generations with an elite pool of {gaConfig.eliteSize}{" "}
            schedules preserved each cycle.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
